/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.2.4-dev at Mon Oct 20 00:05:49 2014. */

#include "messages.pb.h"



const pb_field_t Info_fields[2] = {
    PB_FIELD2(  1, STRING  , REQUIRED, STATIC, FIRST, Info, version, version, 0),
    PB_LAST_FIELD
};

const pb_field_t flash_data_t_fields[3] = {
    PB_FIELD2(  1, UINT32  , REQUIRED, STATIC, FIRST, flash_data_t, address, address, 0),
    PB_FIELD2(  2, BYTES   , REQUIRED, STATIC, OTHER, flash_data_t, data, address, 0),
    PB_LAST_FIELD
};


