/* Automatically generated nanopb header */
/* Generated by nanopb-0.2.4-dev at Mon Oct 20 00:05:49 2014. */

#ifndef _PB_MESSAGES_PB_H_
#define _PB_MESSAGES_PB_H_
#include <pb.h>

#include "protobuf/nanopb.pb.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _Info {
    char version[5];
} Info;

typedef struct {
    size_t size;
    uint8_t bytes[128];
} flash_data_t_data_t;

typedef struct _flash_data_t {
    uint32_t address;
    flash_data_t_data_t data;
} flash_data_t;

/* Default values for struct fields */

/* Field tags (for use in manual encoding/decoding) */
#define Info_version_tag                         1
#define flash_data_t_address_tag                 1
#define flash_data_t_data_tag                    2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Info_fields[2];
extern const pb_field_t flash_data_t_fields[3];

/* Maximum encoded size of messages (where known) */
#define Info_size                                7
#define flash_data_t_size                        137

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
